
'use client';

import { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { Alert, AlertDescription, AlertTitle } from '../ui/alert';
import { AlertTriangle, Check, Copy, Loader2, Sparkles } from 'lucide-react';
import {
  generateNegotiationScript,
  type GenerateNegotiationScriptOutput,
} from '@/ai/flows/generate-negotiation-script-flow';

interface NegotiationScriptDialogProps {
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
  subscription: {
    name: string;
    lastAmount: number;
  } | null;
}

export function NegotiationScriptDialog({
  isOpen,
  setIsOpen,
  subscription,
}: NegotiationScriptDialogProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [script, setScript] =
    useState<GenerateNegotiationScriptOutput['negotiationScript'] | null>(
      null
    );
  const { toast } = useToast();
  const [hasCopied, setHasCopied] = useState(false);

  useEffect(() => {
    if (isOpen && subscription) {
      handleGenerateScript();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, subscription]);

  const handleGenerateScript = async () => {
    if (!subscription) return;
    setIsGenerating(true);
    setError(null);
    setScript(null);
    try {
      const result = await generateNegotiationScript({
        serviceName: subscription.name,
        currentBillAmount: subscription.lastAmount,
      });
      setScript(result.negotiationScript);
    } catch (e: any) {
      setError(e.message || 'An unknown error occurred.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyToClipboard = () => {
    if (!script) return;
    navigator.clipboard.writeText(script);
    setHasCopied(true);
    toast({
      title: 'Copied to Clipboard!',
      description: 'The negotiation script has been copied.',
    });
    setTimeout(() => setHasCopied(false), 2000);
  };

  const handleClose = () => {
    setIsOpen(false);
    setTimeout(() => {
      // Reset state after dialog close animation
      setIsGenerating(false);
      setError(null);
      setScript(null);
      setHasCopied(false);
    }, 300);
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="text-primary" />
            AI Bill Negotiator
          </DialogTitle>
          <DialogDescription>
            Here is a script generated by FinSaathi to help you negotiate your
            bill with {subscription?.name}.
          </DialogDescription>
        </DialogHeader>

        <div className="py-4 space-y-4">
          {isGenerating && (
            <div className="flex flex-col items-center justify-center h-48 text-muted-foreground">
              <Loader2 className="size-8 animate-spin mb-4" />
              <p>Generating your negotiation script...</p>
            </div>
          )}
          {error && (
            <Alert variant="destructive">
              <AlertTriangle className="size-4" />
              <AlertTitle>Generation Failed</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          {script && (
            <div className="relative p-4 bg-muted/50 rounded-md border max-h-[50vh] overflow-y-auto">
              <Button
                size="sm"
                variant="outline"
                className="absolute top-2 right-2"
                onClick={handleCopyToClipboard}
              >
                {hasCopied ? <Check /> : <Copy />}
                {hasCopied ? 'Copied!' : 'Copy'}
              </Button>
              <pre className="whitespace-pre-wrap font-sans text-sm">
                {script}
              </pre>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleClose}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
